# Generated by Django 4.1.2 on 2022-10-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=60, unique=True)),
                ('cuit', models.CharField(default=0, max_length=15, unique=True)),
                ('condicion', models.CharField(choices=[('RI', 'Responsable Inscripto'), ('CF', 'Consumidor Final'), ('EX', 'Excento')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aclaraciones', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('nombre', models.CharField(max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoDelPlata.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.CharField(max_length=100)),
                ('bodega', models.CharField(default='', max_length=100)),
                ('incremento', models.DecimalField(decimal_places=3, max_digits=4)),
                ('unidades', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pruebaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aclaraciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True)),
                ('fecha_cobrado', models.DateTimeField(blank=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True)),
                ('pago', models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia'), ('CH', 'Cheque')], max_length=60)),
                ('entregado', models.BooleanField(default=False)),
                ('aclaraciones', models.CharField(max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoDelPlata.cliente')),
                ('pedidos', models.ManyToManyField(to='MercadoDelPlata.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoDelPlata.producto'),
        ),
    ]
