# Generated by Django 4.1.2 on 2022-10-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='aclaraciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='bodega',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='aclaraciones',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pago',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('TF', 'Transferencia'), ('CH', 'Cheque')], max_length=60),
        ),
    ]
