# Generated by Django 4.0.5 on 2022-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0002_cliente_alter_producto_codigo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
