# Generated by Django 4.1.2 on 2022-10-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0002_alter_pedido_aclaraciones_alter_producto_bodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_cobrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
