# Generated by Django 4.1.2 on 2022-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0003_alter_venta_fecha_cobrado_alter_venta_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_anterior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
