# Generated by Django 4.0.5 on 2022-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0003_pedido_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aclaraciones', models.CharField(max_length=100)),
            ],
        ),
    ]
