# Generated by Django 4.0.5 on 2022-06-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0005_remove_pedido_codigo_pedido_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.ManyToManyField(to='MercadoDelPlata.producto'),
        ),
    ]
