# Generated by Django 4.0.5 on 2022-06-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0006_remove_pedido_codigo_pedido_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MercadoDelPlata.producto'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aclaraciones', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MercadoDelPlata.cliente')),
                ('pedidos', models.ManyToManyField(to='MercadoDelPlata.pedido')),
            ],
        ),
    ]
