# Generated by Django 4.0.5 on 2022-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoDelPlata', '0007_remove_pedido_codigo_pedido_codigo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='nombre',
        ),
    ]
